### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by nunojesus** [mohammadsawas/doctorHaus#1]
Hi,

I have read your work so I decided to creat a logo for you.  I hope you like it and you want to use it. I can give you all the formats of the design free. If you want to make changes please specify.

Greetings 

![logotype blue](https://user-images.githubusercontent.com/34600369/39100628-58b3832a-4684-11e8-9808-b96e374941ab.png)

![logotype blue gray 2](https://user-images.githubusercontent.com/34600369/39100632-6291a57a-4684-11e8-82cd-6d3678ba27ec.png)

**Comment by mohammmod** [comment]
thanks for your help bro and I will try to use this logo and I appreciate this so much from you. 
plus i interested in seeing what else you can do

**Comment by nunojesus** [comment]
Hi, If you want I can make some changes, like the color or the fonts, if you like the logo I can make more images in diferent sizes, black and white color too.

**Comment by mohammmod** [comment]
i would like too.

**Comment by nunojesus** [comment]
Do you prefer other color?

**Comment by nunojesus** [comment]
Here are the designs that I made for you.
See if it´s good for you, to make a pull request.

![icon black](https://user-images.githubusercontent.com/34600369/39388284-cbe8bf4a-4a76-11e8-823a-8352ee060b8d.png)
![icon blue](https://user-images.githubusercontent.com/34600369/39388285-cc24116c-4a76-11e8-83ec-7c2c0bfaa76d.png)
![icon grey](https://user-images.githubusercontent.com/34600369/39388286-cc59679a-4a76-11e8-9d30-b6697a52e87e.png)
![logo black](https://user-images.githubusercontent.com/34600369/39388287-cc86edb4-4a76-11e8-9ce0-70135bd34f9f.png)
![logo blue grey](https://user-images.githubusercontent.com/34600369/39388288-ccc410ae-4a76-11e8-9e34-50dac406b7d7.png)
![logo blue grey2](https://user-images.githubusercontent.com/34600369/39388289-cd05b48c-4a76-11e8-98f9-a1367981195a.png)
![logo blue grey3](https://user-images.githubusercontent.com/34600369/39388290-cd4ae84a-4a76-11e8-88c4-ad2b0b538f5c.png)
![logo blue grey4](https://user-images.githubusercontent.com/34600369/39388291-cd80110a-4a76-11e8-8a21-cea81841cc2d.png)
![logo blue](https://user-images.githubusercontent.com/34600369/39388292-cdb9b8ce-4a76-11e8-93b7-0a5161564652.png)

**Comment by mohammmod** [comment]
this looks so cool man I will just add one of them to the project. Plus I really appreciate it and I like the colors so much.

**Comment by nunojesus** [comment]
Im happy you like it, later today i will make a pull request with all the files. Dont forget to merged :)
Greetings

**Comment by nunojesus** [comment]
Hi are you going to merge the pull request?
